<a href="https://colab.research.google.com/github/Huynhngocthanh/shinzerorin/blob/main/BT_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import numpy as np

_A = [[1, 0, 2], [-1, 3, 2]]
_B = [[3, 2, -2], [1, 2, 0]]
A = np.array(_A)
B = np.array(_B)

print("Ma trận A\n", A)
print("ma trận B\n", B)

Ma trận A
 [[ 1  0  2]
 [-1  3  2]]
ma trận B
 [[ 3  2 -2]
 [ 1  2  0]]


In [ ]:
#Các phép toàn
print("A + B =\n", A + B)
print("A - B =\n", A - B)
print("A * B =\n", A * B)

In [56]:
#Chuyển vị ma trận
C1 = np.transpose(A)
C2 = np.transpose(B)
print("A^T =\n", C1)
print("B^T =\n", C2)

A^T =
 [[ 1 -1]
 [ 0  3]
 [ 2  2]]
B^T =
 [[ 3  1]
 [ 2  2]
 [-2  0]]


In [ ]:
#Ma trận đơn vị
n = int(input("Ma trận đơn vị bậc: "))
dv = np.eye(n)
print(dv)