<a href="https://colab.research.google.com/github/Huynhngocthanh/shinzerorin/blob/main/python_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import numpy as np

_A = [[1, 0, 2], [-1, 3, 2]]
_B = [[3, 2, -2], [1, 2, 0]]
A = np.array(_A)
B = np.array(_B)

print("Ma trận A\n", A)
print("ma trận B\n", B)

Ma trận A
 [[ 1  0  2]
 [-1  3  2]]
ma trận B
 [[ 3  2 -2]
 [ 1  2  0]]


In [58]:
#Các phép toàn
print("A + B =\n", A + B)
print("A - B =\n", A - B)
print("A * B =\n", A * B)

A + B =
 [[4 2 0]
 [0 5 2]]
A - B =
 [[-2 -2  4]
 [-2  1  2]]
A * B =
 [[ 3  0 -4]
 [-1  6  0]]


In [59]:
#Chuyển vị ma trận
C1 = np.transpose(A)
C2 = np.transpose(B)
print("A^T =\n", C1)
print("B^T =\n", C2)

A^T =
 [[ 1 -1]
 [ 0  3]
 [ 2  2]]
B^T =
 [[ 3  1]
 [ 2  2]
 [-2  0]]


In [60]:
#Ma trận đơn vị
n = int(input("Ma trận đơn vị bậc: "))
dv = np.eye(n)
print(dv)

Ma trận đơn vị bậc: 4
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
